# Change these first
owner: patrickc-sb # Your GitHub organization or username, where this repository lives
repo: scriptbased.cloud-status # The name of this repository

sites:
  - name: app-srv01
    url: 116.203.202.135
    check: "tcp-ping"
  - name: proxy01
    url: https://proxy01.scriptbased.cloud
    expectedStatusCodes:
      - 401
  - name: Faunt N8N
    url: $FAUNT_N8N

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: live-status.scriptbased.cloud
  # baseUrl: /uptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Scriptbased.cloud Status
  introTitle: "Service status for Scriptbased.net Webapps"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
